config/routes.rb
Rails.application.routes.draw do
  get 'menus/index'
  devise_for :users

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end

  root 'home#index'

  resources :categories, only: %i[index new show create destroy update edit] do
    resources :transactions, only: %i[index new show create destroy update edit]
  end
  resources :menus
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :group, class_name: 'Group', foreign_key: 'group_id'

  validates :name, presence: true, length: { in: 3..250 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :entities, foreign_key: 'group_id', dependent: :delete_all

  validates :name, presence: true, length: { in: 3..200 }
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'user_id', dependent: :delete_all
  has_many :entities, foreign_key: 'user_id', dependent: :delete_all

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
require 'open-uri'

class CategoriesController < ApplicationController
  def index
    @groups = Group.left_outer_joins(:entities)
      .select('groups.*, COUNT(entities.id) as transactions_count, sum(entities.amount) as total_amount')
      .group('groups.id')
      .where(user_id: current_user.id)
  end

  def show
    @group = Group.left_outer_joins(:entities)
      .select('groups.*, COUNT(entities.id) as transactions_count, sum(entities.amount) as total_amount')
      .group('groups.id')
      .find(params[:id])
    @transactions = Entity.where(group_id: params[:id]).order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.create(group_params)
    redirect_to categories_path if @group.save
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def show
    @entity = Entity.find(params[:id])
    @category = Group.find(params[:category_id])
  end

  def new
    @entity = Entity.new
    @categories = Group.where(user_id: current_user.id)
  end

  def create
    @entity = Entity.new(name: params[:entity][:name], amount: params[:entity][:amount], user_id: current_user.id,
                         group_id: params[:entity][:category])

    redirect_to category_transaction_path(params[:entity][:category], @entity.id) if @entity.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/index.html.erb
<header class="categories-header">
<%= render "shared/hamburger"%>
    <h2 class="big-title">CATEGORIES</h2>
    <%= link_to "Logout",
      destroy_user_session_path,
      data: { turbo_method: :delete },
      class: 'logout'
    %>
</header>


<div class="categories index-category">
  <% @groups.each do |category|%>
   <a href="<%= category_path(category.id)%>">
   
     <div class="category">
       <div class="icon-container">
         <img src="<%=category.icon %>" alt="" class="category-icon">
       </div>

       <p class="category-name"><%=category.name %></p>
       <p class="total-amount">Total amount: $<%=0 + category.total_amount.to_i%></p>
       <p class="num-of-transactions">Transactions: <%=category.transactions_count%></p>
     </div>
   </a>
  <% end %>
</div>


<div class="link-wrap">
  <a href="<%=new_category_path %>" class="add-a-new-category">Add a new Category</a>
</div>

app/views/categories/new.html.erb
<header class="categories-header">
    <a href="<%=categories_path %>" ><img src="/images/arrow_back.png" alt="" class="arrow-back"/></a>
    <h2 class="big-title">ADD CATEGORY</h2>
</header>

<%= form_with model: @group, url: categories_path, method: :post, data: { turbo: false } do |form| %>
  <div class="field top-field">
    <%= form.label :icon %>
    <%= form.text_field :icon, class: 'form-control', placeholder: 'http://Icon.png' %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Category name here' %>
  </div>

   <div class="actions">
    <%= form.submit "Save"  %>
  </div>
<% end %>

app/views/categories/show.html.erb
<header class="categories-header">
<%= render "shared/hamburger"%>
    <h2 class="big-title">TRANSACTIONS</h2>
</header>

<div class="gift-credit">
  <p class="gift-amount">total amount</p>
  <p class="gift-amount-total">$<%=0 + @group.total_amount.to_i%></p>
</div>

<div class="categories">
  <% @transactions.each do |transaction|%>
    <a href="<%=category_transaction_path(params[:id],transaction.id) %>">
     <div class="category">
       <div class="icon-container">
         <img src="<%=@group.icon %>" alt="" class="category-icon">
       </div>
       <p class="category-name"><%=transaction.name %></p>
       <p class="tranzaction-price">$<%=transaction.amount %></p>
       <p class="tranzaction-date"><%=transaction.created_at.strftime("%FT%T") %></p>
     </div>
    </a>
  <% end %>
</div>

<div class="link-wrap">
  <a href="<%=new_category_transaction_path(params[:id]) %>" class="add-a-new-category">Add a new Transaction</a>
</div>

app/views/home/index.html.erb
<main class="splash-screen">
<h1>Budget Monitor</h1>
<div class="buttons-sign">
  <a href="<%=new_user_session_path %>" class="login">LOG IN</a>
  <a href="<%=new_user_registration_path %>">SIGN UP</a>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetMonitor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
<div class="menu">
  <div class="user-creadentials">
    <div class="user-avatar-wrap">
     <img src="https://icon-library.com/images/male-user-icon/male-user-icon-13.jpg" alt="" class="user-avatar">
    </div>
    <h6><%=current_user.name %></h6>
  </div>
  <div class="link_to">  
    <img src="/images/category.png" alt="" class="icon-link"/>
    <a href="<%=categories_path %>">Categories</a>
  </div>  
  <div class="link_to">  
    <img src="/images/add_category.png" alt="" class="icon-link"/>
    <a href="<%=new_category_path %>">Add Category</a>
  </div>
  <div class="link_to">  
    <img src="/images/tranzaction.png" alt="" class="icon-link"/>
    <a href="<%=new_category_transaction_path(2) %>">Add Transaction</a>
  </div>
</div>

app/views/shared/_hamburger.html.erb
<a href="<%=menus_path %>" class="hamburger-link">
<div class="hamburger">
  <div></div>
  <div></div>
  <div></div>
</div>
</a>

app/views/transactions/new.html.erb
<header class="categories-header">
    <a href="<%=categories_path %>" ><img src="/images/arrow_back.png" alt="" class="arrow-back"/></a>
    <h2 class="big-title">NEW TRANSACTION</h2>
</header>

<%= form_with model: @entity, url: category_transactions_path, method: :post, data: { turbo: false } do |form| %>

  <div class="field top-field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'jordan 3' %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: 'form-control', placeholder: '0' %>
  </div>

 <div class="select-category">
  <span>select a category</span>
   <%@categories.each do |category|%>
    <div class="radio-btn">
     <%= form.label :category, category.name, value: "345"  %>
     <%= form.radio_button :category, category.id %>
    </div> 
   <%end%> 
 </div>

 <div class="actions">
    <%= form.submit "Save"%>
  </div>
<% end %>